"""
Question Answer Service

Answers educational questions using the provided context.
"""

from backend.config import get_llm


class QuestionAnswerService:
    """
    Service responsible for answering educational questions.
    """

    def __init__(self):
        self.llm = get_llm()

    def answer_question(self, question: str, context: str) -> str:
        """
        Answer a question using ONLY the supplied educational context.

        Args:
            question (str): User's question.
            context (str): Educational content.

        Returns:
            str: Answer generated by the LLM.
        """

        prompt = f"""
You are an educational AI assistant.

Answer the question ONLY using the provided context.

Rules:
- Do not invent information.
- If the answer is not present in the context,
  respond with:
  "The provided educational context does not contain the answer."

Educational Context:
{context}

Question:
{question}

Answer:
"""

        response = self.llm.invoke(prompt)

        return response.content.strip()


# ----------------------------------------------------
# Testing
# ----------------------------------------------------

if __name__ == "__main__":

    service = QuestionAnswerService()

    context = """
Python is a high-level programming language.
It supports object-oriented programming,
functional programming, and procedural programming.
"""

    question = "What programming paradigms does Python support?"

    answer = service.answer_question(
        question=question,
        context=context
    )

    print(answer)