"""
==========================================================
Response Aggregator

Project:
Educational Content Generator AI

Module:
Orchestrator Agent

Purpose:
Aggregates outputs generated by different agents into
a unified response for the client.

Author:
Team Orchestrator
==========================================================
"""

from typing import Any, Dict

from state import AgentState

from utils.logger import get_logger
from utils.constants import ResponseStatus

logger = get_logger(__name__)


class ResponseAggregator:
    """
    Aggregates outputs from multiple agents into
    a standardized response.
    """

    @staticmethod
    def aggregate(
        state: AgentState,
    ) -> Dict[str, Any]:
        """
        Create the final response from AgentState.
        """

        logger.info("Aggregating final response.")

        response = {

            "status": ResponseStatus.SUCCESS.value,

            "request_id": state.get("request_id"),

            "workflow": state.get("workflow"),

            "intent": state.get("intent"),

            "data": {

                "processed_content":
                    state.get("processed_content"),

                "educational_output":
                    state.get("educational_output"),

                "multimedia_output":
                    state.get("multimedia_output"),

            },

            "error": state.get("error"),

        }

        logger.info("Response aggregation completed.")

        return response